version: '3'

services:
  web:
    image: nginx:mainline-alpine
    depends_on:
      - php
    env_file:
      - .env
    networks:
      - backend
    ports:
      - 8080:80
    restart: always
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
  php:
    build: .
    env_file:
      - .env
    networks:
      - backend
    restart: always

networks:
  backend:
